services:
  app:
    build: .
    environment:
      PORT: 3000
    ports:
    - "3000:3000"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: main