name: ci

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
        -
          name: Checkout
          uses: actions/checkout@v2
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        -
          name: Login to GitHub Package Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ GITHUB.REPOSITORY_OWNER }}
            password: ${{ SECRETS.GHCR_TOKEN }}
        -
          name: build, tag and push api
          id: build_api
          env:
            DOCKER_REGISTRY: ghcr.io
            DOCKER_USER: ${{ GITHUB.REPOSITORY_OWNER }}
            DOCKER_REPOSITORY: ${{ GITHUB.REPOSITORY }}
            IMAGE_TAG: ${{ GITHUB.SHA }}
          run: |
            docker build -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG .
            docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG
            docker tag $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG $DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest
            docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest
            echo "::set-output name=image::$DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest"